# Sample config for Prometheus.

global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:

  - job_name: jenkins
    static_configs:
      - targets: ["192.168.56.90:9100"]

  - job_name: Nexus
    static_configs:
      - targets: ["192.168.56.91:9100"]

  - job_name: sonarqube
    static_configs:
      - targets: ["192.168.56.92:9100"]

  - job_name: backend
    static_configs:
      - targets: ["192.168.56.93:9100"]

  - job_name: ctfrontend
    static_configs:
      - targets: ["192.168.56.95:9100"]

  - job_name: cpfrontend
    static_configs:
      - targets: ["192.168.56.97:9100"]